// ---------------------------------------------------------------------------
// Aditya Guruji rules library — bundled seed dataset.
//
// 190 reference principles across 8 categories (Pathakadhipathi, Longevity,
// Prediction Method, Dasa-Bhukthi, Weekly/Transit, Saturn Aspect, Mercury
// Subathuvam, Bhukthi-Antara Timing), each with EN/TA/HI title + body and
// derived planet/house tags (0=Sun..8=Ketu; houses 1..12).
//
// The dataset lives in guruji-rules.seed.json (generated by build_rules_ts.py
// from guruji-rules.data.json + translations). esbuild inlines JSON imports
// natively, and tsx resolves them in dev, so this ships in both prod and dev.
// storage.ts imports RULES_SEED and idempotently upserts it on startup.
// ---------------------------------------------------------------------------
import seed from "./guruji-rules.seed.json";

export type SeedRule = {
  ruleNo: number;
  astrologer: string;
  categoryKey: string;
  categoryEn: string;
  categoryTa: string;
  titleEn: string;
  titleTa: string;
  titleHi: string;
  bodyEn: string;
  bodyTa: string;
  bodyHi: string;
  planets: number[];
  houses: number[];
};

export const RULES_SEED: SeedRule[] = seed as SeedRule[];
